name: CI

on:
  push: 
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build
        uses: docker/build-push-action@f64672cf50fa6f34ab7b194daf79d0161632a3ae
        with:
          context: .
          push: false
