name: CI

on:
  push: 
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build
        uses: docker/build-push-action@9a57217389f1c89cb7c6bf96972f839d187aaf5b
        with:
          context: .
          push: false
