name: CI

on:
  push: 
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Build
        uses: docker/build-push-action@ef1fb9688fc3626d0fd5e462f502cbbdc6456feb
        with:
          context: .
          push: false
